module Facts
@facts = ["The Philippines are named after King Philip II of Spain. Explorer Ruy López de Villalobos named the Eastern Visayas Felipenas first, and the name was later applied to the entire archipelago. The country's official name is the Republic of the Philippines.",
"The Philippines was the first country in Southeast Asia to gain independence after World War II, in 1946.",
"The Philippines has the highest rate of discovery of new animal species with 16 new species of mammals discovered just in the last 10 years.",
"Monkey Eating Eagle The Philippine, or monkey-eating, eagle is the largest of all eagles and was declared the national bird of the Philippines in 1985",
"The national symbol of the Philippines is the Philippine, or monkey-eating, eagle. It is the largest of all eagles and was declared the national bird of the Philippines in 1995. It stands up to 3.3 feet (1 m) in height and has a wingspan of almost 7 feet (2 m). It is critically endangered; there may only be around 180–500 eagles remaining. Killing one is punishable by Philippine law by 12 years in jail and a heavy fine.",
"Human trafficking is a problem in the Philippines. The country has the fourth largest number of prostituted children in the world. There are estimated to be 375,000 women and girls in the sex trades, mostly between the ages of 15 and 20, though some are as young as 11.",
"Current president Benigno Aquino III is the first president of the Philippines to be a bachelor and he is the son of ex-president Corazon Aquino, making him the second president to be a child of a former president (his predecessor Gloria Arroyo was the other).",
"Pop singer Bruno Mars is half Filipino and half Puerto Rican. His childhood nickname was 'Little Elvis.' His real name is Peter Gene Bayot Hernandez. His stage name was inspired by the chubby wrestler Bruno Sammartino.",
"The world's biggest pair of shoes was made in Marikina City, Philippines, in 2002. The wingtips measured about 17.4 feet (5.3 m) in length, 7.9 feet (2.4 m) in width, and almost 6.6 feet (2 m) in height. Their cost was 2 million Philippine pesos.",
"The world record for most women breastfeeding simultaneously was 3,541, set in Manila, Philippines, on May 4, 2006.",
"Of the top 10 largest shopping malls in the world, three are found in the Philippines: SM Megamall, SM North Edsa, and SM Mall of Asia.",
"The world's largest pearl was discovered by a Filipino diver in the Palawan Sea in 1934. Known as the 'Pearl of Lao Tzu,' or 'Pearl of Allah,' the gem weighs 14 pounds (6.35 kg) and measures 9.5 inches (24 cm) long and 5.5 inches (.4 cm) in diameter. It has a value of over US$40 million. It is believed to be 600 years old.",
"The Philippines is the world's largest exporter of coconuts and tropical fruits, such as papaya and mangosteen.",
"Some Filipinos are wary of the number 13 and will avoid having 13 people at a table. Also, steps to the main entrance of a house should not fall on a number divisible by three. Superstitious Filipinos will not travel or bathe on Holy Thursday or Good Friday during Holy Week, the week before Easter.",
"Skunk Eating Strawberry Skunks can be found in only three countries in the world, the United States, Indonesia, and the Philippines, where they are called stink badgers",
"The only place in the world where skunks are found other than America is Indonesia and the Philippines, where they are called stink badgers.",
"President Benigno Aquino III of the Philippines is known as 'Noynoy,' and two of his sisters' nicknames are 'Pinky' and 'Ballsy.'",
"Christian names in the Philippines include Bing, Bong, Bambi, Bogie, Girlie, Peanut, and Bumbum.",
"Jellyfish Lake in the Philippines contains more than 13 million jellyfish.",
"The Philippines is the second largest archipelago in the world and is made up of 7,107 islands located in the South China Sea, Philippine Sea, Sulu Sea, Celebes Sea, and the Luzon Strait.",
"The Philippines is the only majority Christian nation in Asia. Eighty percent of its population identifies as Roman Catholic.",
"The Philippines has a population of more than 100 million people, which makes it the 12th most populous country in the world. Its annual growth rate of around 2% makes it one of the fastest growing countries in the world.",
"Mt. Pinatubo on the Philippine island of Luzon erupted on June 15, 1991, and created the largest mushroom cloud in the world. Its eruption ejected 10 billion metric tons of magma and 20 million tons of sulphur dioxide into the stratosphere.",
"According to Filipino custom, it is considered rude to open gifts immediately after they are given.",
"The Philippines is the only country in the world whose flag is hoisted upside down when the country is at war.",
"Philippines Capitol Manila Manila is considered to be the world's most densely populated city with a population of 1,660,714 and an area of 24 square miles (38.55 square km)",
"Manila, the capital of the Philippines is considered the world's most densely populated city in the world. With a population of 1,660,714 and an area of just 24 square miles (38.55 square km), it has a population density of 55,446 people per square mile (43,079 people per square km).",
"The Conus gloriamus, the rarest and most expensive seashell in the world, is one of the 12,000 species of seashells found in the Philippines. The first examples of these shells sold at auction for about US$5,000.",
"The yo-yo had its beginnings as an ancient Filipino studded hunting weapon attached to a 20-foot rope. The modern yo-yo was invented by a Filipino American, and its name yóyo comes from the Filipino language Ilocano and means 'come back.'",
"The Philippines is home to the world's longest snake, the Reticulated Python (Python reticulatus), which also happens to be the world's longest reptile. It can grow to 28.5 feet (8.7 m) in length.",
"There are between 120 and 175 individual languages spoken in the Philippines, 171 of which are living while the other four no longer have any known speakers. English and Filipino, based on Tagalog, are the country's two officially recognized languages.",
"The Philippines is the world's largest supplier of nurses, supplying roughly 25% of all overseas nurses worldwide.",
"The antibiotic erythromycin was invented by Filipino Dr. Abelardo Aguilar in 1949. He sent a sample to his employer, the Eli Lilly pharmaceutical company, which promptly patented it. Erythromycin is used for people who are allergic to penicillin and has saved millions of lives.",
"The Puerto Princesa Subterranean River in Palawan, Philippines, is 5 miles (8.2 km) long. Until the discovery of a 6.2-mile (10-km) underground river in Mexico, the Puerto Princesa River was known as the longest subterranean waterway in the world.",
"The English words 'boonies' and 'boondocks' is actually based on the Filipino/Tagalog word for 'mountain,' bundok. The word entered the North American vernacular in the 1940s, probably brought back by soldiers stationed in the Philippines during World War II.",
"Philippine Christmas Lantern Costing between $US 11,300 to $15,800 to build, only about 10 parols, huge Christmas lanterns, are made each year to compete in the Giant Lantern Festival in the Philippines",
"San Fernando, Philippines, is known as the 'Christmas Capital of the Philippines' and is most famous for its parols (giant Christmas lanterns), which symbolize the star of Bethlehem and can rise 20 feet (6 m) in the air. Only about 10 giant parols are produced each year to compete in the Ligligan Parul (Giant Lantern Festival). Each parol costs around US$11,300 to $15,820 to build.",
"The Taal Volcano on the Philippine island of Luzon is one of the world's 17 Decade Volcanoes, which are volcanoes being specially monitored given their active state and explosive history. Taal is also located in a lake, which has another lake inside of it, with an even smaller island inside of that lake.",
"A Filipino named Roberto del Rosario patented the first working karaoke machine in 1975, calling it the 'Sing Along System.' The Japanese later translated its name to 'karaoke,' which means 'singing without accompaniment.'",
"In the Philippine island province of Camiguin, there are more volcanoes (7) than towns (5). There hasn't been an eruption since the mid-1950s, but the island has the most number of volcanoes per square kilometer in the world.",
"The University of Santo Tomas was founded in Manila, Philippines, by Dominican monks in 1611. It is the world's largest Catholic university in terms of population. Both it and the University of San Carlos in Cebu City, founded in 1595, are older than Harvard University, which was not founded until 1636.",
"Over 11 million Filipinos work overseas, which constitutes about 11% of the entire population of the Philippines. Filipinos are the second-largest Asian-American group in the United States, next to the Chinese.",
"The Mindanao Trench, which is near the Philippines in the Pacific Ocean, is the second deepest spot under the world's oceans at 6.5 miles, or 34,440 feet (10,497 m). It was first explored by the German ship Emden in 1927.",
"Filipinos observe the world's longest Christmas season. It begins with the playing of carols in September and officially ends in January with the Feast of the Three Kings. As part of the festivities, they celebrate Simbang Gabi, or Night Mass, where Catholics attend nine services in a row leading up to Christmas Eve. If a person attends all nine masses, it is said their wish will be granted. Filipinos' Christmas feasts are called Noche Buena and compare to America's Thanksgiving.",
"Filipino-American Eleanor 'Connie' Concepcion Mariano was the personal physician to President Bill Clinton. She was also the youngest captain and first female to be named Rear Admiral in the U.S. Navy.",
"War journalist Carlos Peňa Rómulo was the first Asian/Filipino to win the American Pulitzer Prize for Correspondence in 1942. He was also the first Asian to become president of the United Nations.",
"The Philippine capital city of Manila was named after the white-flowered mangrove plant, the Nilad, or Scyphiphora hydrophyllacea. It is a tree with white, star-shaped flowers but yields dark blue dye, which is why in other countries it is called the Indigo tree.",
"Philippine President Marcos Ferdinand Marcos, the first elected Filipino president, has never been properly buried, even though he has been dead for almost two decades",
"Even though the first elected Filipino president, Ferdinand Marcos, has been dead for almost two decades, his body has never been properly buried—it remains 'on ice' while officials quibble about whether he should buried in the cemetery reserved for Filipino heroes and past presidents.",
"Of the eight known species of giant clams in the world, seven are found in the Philippines.",
"The Philippines is home to the world's smallest hoofed animal, the Philippine mouse-deer. Locally known as the Pilandok (Tragulus nigricans), this creature stands about 15.8 inches (40 cm) tall at the shoulder level.",
"One of the most interesting and traditional Philippine dishes is balut, which is essentially a boiled, fertilized duck egg with a half-formed chick inside. It is said to be an aphrodisiac. Other unique dishes include camaro, which are field crickets cooked in soy sauce, vinegar, and sugar; papaitan, which is a goat or cow innards stew flavored with bile; Soup #5, which is a soup made out of bull testicles; and asocena, or dog meat.",
"The Philippines experiences one large-magnitude earthquake (7.75 or higher on the Richter scale) every 10 years, seven earthquakes of major magnitude (7.0 to 7.4) every 10 years, and five earthquakes of moderate magnitude (6.0 to 6.9) every year.",
"The Philippines is the world's second biggest geothermal producer after the United States with 18% of the country's electricity needs being met by geothermal power.",
"The most active typhoon season for the Philippines was 1993, when 19 moved through the country. A typhoon is a strong tropical cyclone equivalent to a hurricane in North and Central America. The highest wind velocity for a typhoon that crossed the Philippines was recorded in Virac on November 30, 2006, when Typhoon Reming had a peak gust of 198 mph (320 kph).",
"After Philippine president Ferdinand Marcos and his wife Imelda fled the Malacañang Palace, she famously left behind 15 mink coats, 508 gowns, 1,000 handbags, and 1,060 pairs of shoes—from a collection rumored to contain around 3,000 pairs.",
"The anti-lock braking systems (ABS) used in Mercedes-Benz, BMW, and Volvo cars are made in the Philippines. Ford, Toyota, and Nissan are the most prominent automakers manufacturing cars in the country.",
"The jeepney is sometimes referred to as the 'King of the Philippine roads.' It is a descendant of the Jeeps American troops drove in the Philippines during World War II. Second- and third-generation jeepneys have air conditioning units and closely resemble minibuses. They can carry up to 16 passengers.",
"The traditional embroidered Filipino male garment, the barong Tagalog or baro, is woven from piña, pineapple plant fibers, or jusi, banana tree fibers, and worn on formal occasions.",
"Philippine Woman Texting The Philippines is considered the text capital of the world because every day 35 million Filipinos send about 450 millions SMS messages",
"The Philippines is considered the text capital of the world. Every day, 35 million Filipinos send about 450 million SMS messages. This is more than the total number of daily text messages sent in the U.S. and Europe combined.",
"In the rural Philippines, most women give birth at home and then have the baby's placenta buried beneath the house, often with an object symbolizing what the parents hope the child will grow up to be. In the cities, this practice is prohibited by the health authorities.",
"Santelmo, or Santo Elmo, is a fireball seen by dozens of Filipinos, especially those who live in the Sierra Madre Mountains. It was scientifically explained as electrical fields that have diverged from the power lines. However, sightings have been reported since the Spanish era (16th–19th centuries). There have also been similar sightings in the Alps and Himalayas.",
"Cockfighting is a centuries-old blood sport, popular since the times of ancient Persia, Greece, and Rome. In the Philippines, it is still very popular, and the country has hosted several 'World Slasher Cups,' staged in Manila's Araneta Coliseum. The world's leading game fowl breeders gather twice a year for this event.",
"The Filipino national dish may very well be the adobo, which is a dark stew of chicken and/or pork cooked in soy sauce, vinegar, crushed garlic, bay leaf, and black peppercorns.  In Spanish, adobo originally meant 'sauce' or 'seasoning.' The Filipino version is actually indigenous to the islands, dating back to a dish cooked up long before Magellan's arrival.",
"Manny Pacquiao could currently be regarded as the world's best boxer pound per pound. He has four major titles under his belt: the WBC International Super Featherweight Title, the RING Featherweight Title, the IBF Super Bantamweight Title, and the WBC Flyweight Title. Out of 45 fights, 'Pacman,' as he is called, has won 40, with 31 by knockout.",
"Phillipines Facts The Phillipines Basketball Association is the first and oldest basketball in Asia",
"Basketball is the most popular sport in the Philippines. The Philippines Basketball Association (PBS) is the first and oldest league in Asia and the second oldest in the world after the United States' National Basketball Association (NBA).",
"Tanduay rum dates back to 1854 and today remains the Philippines' spirit of choice. Made from sugar cane milled on the island of Negros, it's frequently cheaper than bottled water.",
"The Aswang, a mythical female vampire-like figure in Filipino folklore who eats unborn children, has been the subject of at least one American horror film and was featured in an episode of the CW television hit Supernatural called 'Fresh Meat.'",
"The Philippines is the world’s leading producer of coconuts, having produced 19.5 million tons of the fruit in 2010.",
"According to the 2000 census, 52 million people in the Philippines speak English, making it the fifth largest English-speaking nation behind the U.S., India, Pakistan, and the U.K.",
"Of the top 10 largest shopping malls in the world, three are found in the Philippines: SM Megamall, SM North Edsa, and SM Mall of Asia.",
"The Puerto Princesa Subterranean River in Palawan is 8.2 kilometers long. Until the discovery of a 10-kilometer underground river in Mexico, the Puerto Princesa River was the longest subterranean waterway in the world.",
"Ferdinand Magellan arrived in the Philippines in 1521, marking the start of the archipelago’s colonization under Spanish rule, a 377-year period that lasted until 1898.",
"The islands were dubbed “the Philippines” after King Philip II of Spain.",
"As a result of the Spanish influence, the country is predominantly Christian with 90% of the population practicing some mode of Christianity, the vast majority being Roman Catholic.",
"The world’s largest Christmas lantern was illuminated in San Fernando, Pampanga on Dec. 24, 2002. The structure was 26.8 meters in diameter and cost five million Philippine pesos.",
"Pope John Paul II offered a mass to about five million Filipinos on Jan. 18, 1995, at Luneta Park in Manila. The event went into the Guinness Book of World Records as the Biggest Papal Crowd at the time.",
"In 2009, about 1.39 billion SMS messages were being sent in the Philippines daily. The country was one of the earliest adopters of text messaging, earning the moniker “text capital of the world” from the mid ’90s to the early 2000s.",
"The English word ‘boondocks’ is actually a Filipino loanword: the Tagalog word for ‘mountain’ is ‘bundok.’",
"The word entered the North American vernacular in the 1940s, just as the Philippines became involved in the Second World War.",
"Taal Volcano in Talisay, Batangas, is one of the world’s 17 Decade Volcanoes — volcanoes that need to be looked after given their active state and explosive history. It’s also located in a lake, and has a lake inside it, with an even smaller island in it!",
"The amount of sulfur dioxide expelled by Mount Pinatubo during its eruption on Jun. 15, 1991, created a two-year haze of sulfuric acid all over the world. It caused global temperatures to drop by 0.5 °C (0.9 °F).",
"A Filipino named Roberto del Rosario made the karaoke machine in 1975, but a Japanese musician invented it four years earlier. Del Rosario, however, was the first to patent the product, which makes him the first patented producer of the karaoke.",
"In the province of Camiguin, there are more volcanos (seven) than towns (five). There hasn’t been an eruption since the mid 1950s, but the island has the most number of volcanoes per square kilometer in the world.",
"The positioning of the Philippine flag’s colors indicate a message. If it is flown with the red stripe on top, the nation is in a state of war. Otherwise, during peacetime, the blue is on top.",
"The modern yo-yo takes its name from a word in the Philippine language Ilocano, yóyo.",
"The University of San Carlos in Cebu City was founded by Spanish Jesuits in 1595, making it the oldest school in the Philippines.",
"Then in 1611, the University of Santo Tomas (or, lovingly, “Usté”) was founded in Manila by the Dominican Order. It is the world’s largest Catholic university in terms of population. Both it and University of San Carlos are older than Harvard, which was not founded until 1636.",
"The cone of the sea snail Conus gloriamaris is a highly valued collector’s item, the first examples of which were found in the Philippines and sold at auction for upwards of $5,000.",
"In 2002, the world’s biggest pair of shoes were made in Marikina City. The wingtips clock in at about 5.3 meters in length, 2.4 meters in width, and almost 2 meters in height. They cost two million Philippine pesos.",
"Manila, the capital city of the country, takes its name from a white flower that grew on mangrove trees, locally known as nilad. ‘May nilad’ can be translated to mean ‘there are nilad there.’",
"The rice terraces of the Philippine Cordilleras are a UNESCO World Heritage Site. The terraces were built about 2,000 years ago and — thanks to the rough terrain keeping settlers out — remain as they would have been in pre-colonial times.",
"The Philippines has won at least eight major international beauty pageant titles: two for Miss Universe; five for Miss International; and at least one for Miss World, the current titleholder being Megan Young.",
"About 25 years before the first book was printed in the United States, the Tagala, the first Filipino-Spanish dictionary, was printed in 1613.",
"After the Second World War, the Philippine jeepney was born out of the G.I. Jeeps American soldiers brought to the country in the 1940s. It’s Pinoy upcycling!",
"The Philippines’ approximately 300,000 square kilometers (115,831 sq mi.) of land area are spread over 7,107 islands.",
"This gives the country 36,289 kilometers (22,549 mi.) of coastline and puts the Philippines at fifth place for the longest discontinuous coastline in the world.",
"Depending on the method of classification, there are 125 to 170 languages in use in the Philippines, such as Tagalog, Cebuano, Ilocano, Hiligaynon, Bicolano, Waray, and Kapampangan.",
"The Philippines welcomed its 100-millionth citizen on July 27, 2014, making the country the seventh most populated country in Asia and the 12th in the world."]

def self.facts
    @facts
end

def self.random_fact
    @facts.shuffle.first
end

end